{
 "title": "Temperature API - Logs Dashboard",
 "tags": [
  "logs",
  "temperature-api"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "API Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{service=\"temperature-api\"} |= ``"
    }
   ]
  },
  {
   "title": "Logs par niveau",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({service=\"temperature-api\"} [5m])) by (level)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Erreurs récentes",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{service=\"temperature-api\"} |= \"ERROR\""
    }
   ]
  },
  {
   "title": "ETL Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{service=\"spark-etl\"} |= ``"
    }
   ]
  },
  {
   "title": "Windy Streaming Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{service=\"spark-windy-streaming\"} |= ``"
    }
   ]
  }
 ]
}